### ISSUE TITLE
Styling issue React app 

### ISSUE THREAD

**Issue by MaloRchrd** [MaloRchrd/first-react-app#1]
Hello everyone. 

I'm new to developpement and this is my first app, i used react native which i 'm new to and i got issue with styling. 
When my class are in my `index.ios.js` file it works perfectly but when i moved then to a seperate file`styles.js` and import the file to the index with this line `var styles = require('./styles')` , the style does'nt show up anymore 

ping @thaume

**Comment by thaume** [comment]
A la place de ton `var styles = require('./styles');` Essaye ça :

```
import { styles } from './styles';
```

Tu pourras ensuite accéder aux styles via `styles.myclass`.

Une bonne pratique c'est aussi de bien mettre les `import` en tête de fichier.

**Comment by MaloRchrd** [comment]
J'avais testé cette méthode mais ça ne fonctionne pas non plus. 
J'ai fait un nouveau commit avec les changements 
l'erreur qu'il renvoie c'est ça. 

Soit j'appelle pas bien la class je le fait comme ça 

`<View style={styles.container} >`

Soit j'ai un problème dans le fichier `style.js`

<img width="369" alt="capture d ecran 2016-10-12 a 12 48 08" src="https://cloud.githubusercontent.com/assets/17042850/19307334/28b6b05a-907a-11e6-9908-9e943ddc6121.png">

**Comment by MaloRchrd** [comment]
Ca fonctionne avec 

`import styles from './styles';`
