### ISSUE TITLE
Bug sur l'élément navigateur ios. 

### ISSUE THREAD

**Issue by MaloRchrd** [MaloRchrd/first-react-app#2]
Hello @thaume

J'ai un nouveau bug,  (Dsl ça fait déjà plus d'une heure que je galère dessus, alors je prend mon jocker, je fait appelle à un ami. ) 

En gros sur mon commit d'avant tout fonctionnait très bien.  
Le `NavigatorIOS` étais nickel avant que j'isole  `MediaListView` dans un fichier dédié ( de `index` --> `media-list-view.js`) 

Maintenant j'ai cette erreur que je ne comprend pas 

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `NavigatorIOS`.

J'ai importé mon media-list-view comme ça en haut de la page 

`import MediaListView from './media-list-view';`

Help :-/

**Comment by MaloRchrd** [comment]
J'ai trouvé ça mais ça ([ici](https://github.com/wix/react-native-navigation)) me donne pas la solution 

`For example, this package replaces the native NavigatorIOS that has been abandoned in favor of JS-based solutions that are easier to maintain. For more details see in-depth discussion here.`

Et ça aussi mais je t'avoue être un peu perdu. 
https://github.com/facebook/react-native/issues/6184

**Comment by thaume** [comment]
Pars sur [Navigator](https://facebook.github.io/react-native/docs/navigator.html), tu pourras normalement migrer sur NavigationExperimental lorsqu'il sera finalisé.

**Comment by MaloRchrd** [comment]
Le problème était  autre j'ai réussi a faire fonctionner `navigatorIOS` en revenant sur le commit d'avant.

**Comment by thaume** [comment]
Yes mais attention, NavigatorOS n'est plus mis à jour
